### PR TITLE
Setup eslint and more dev tools

### PR DESCRIPTION
**Pull request by mattmilburn**
**This PR installs and configures eslint and other dev tools 🙌🏻** 

* Install `eslint` and it's many related packages.
* Adjust `prettier` config to work with `eslint`.
* Install `husky` and `lint-staged` to enable code formatting checks in pre-commit hook.
* Add `lint` and `format` scripts to package.json.
* Add `.editorconfig` file.

### CODE REVIEW

**Comment by BorysShulyak** [comment]
@mattmilburn May be it would be useful to add eslint for jest. I use this packages on my production project and they are really helpful: 
eslint-plugin-jest
eslint-plugin-jest-formatting

**Comment by mattmilburn** [comment]
> 

@BorysShulyak Since you have created the PRs https://github.com/mattmilburn/strapi-plugin-do-not-delete/pull/8 and https://github.com/mattmilburn/strapi-plugin-do-not-delete/pull/11, do you want to help close out those comments and we can merge those into staging first?

Then we can rebase this branch and install the eslint jest plugins with an actual jest configuration from your PR. Do you have a preference on the settings for those plugins or just go with out-of-the-box settings?

**Comment by mattmilburn** [comment]
> @mattmilburn May be it would be useful to add eslint for jest. I use this packages on my production project and they are really helpful: eslint-plugin-jest eslint-plugin-jest-formatting

@BorysShulyak Since you have created the PRs https://github.com/mattmilburn/strapi-plugin-do-not-delete/pull/8 and https://github.com/mattmilburn/strapi-plugin-do-not-delete/pull/11, do you want to help close out those comments and we can merge those into staging first?

Then we can rebase this branch and install the eslint jest plugins with an actual jest configuration from your PR. Do you have a preference on the settings for those plugins or just go with out-of-the-box settings?

**Comment by BorysShulyak** [comment]
> @BorysShulyak Since you have created the PRs #8 and #11, do you want to help close out those comments and we can merge those into staging first?
> 
> Then we can rebase this branch and install the eslint jest plugins with an actual jest configuration from your PR

@mattmilburn Sure! I have applied your suggestions on PR https://github.com/mattmilburn/strapi-plugin-do-not-delete/pull/11. So firstly, we could merge it. Secondly, I'm going to rebase the branch of https://github.com/mattmilburn/strapi-plugin-do-not-delete/pull/8 and cover the implemented comparators with tests.

> Do you have a preference on the settings for those plugins or just go with out-of-the-box settings?

It actually works fine out of the box.

**Comment by mattmilburn** [comment]
@BorysShulyak This is now ready to merge, so your PR https://github.com/mattmilburn/strapi-plugin-do-not-delete/pull/8 can be next 👍🏻

**Pull request merged**
